# Generated by Django 5.2.14 on 2026-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
